language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
env:
- WITH_RUGGED=no
- WITH_RUGGED=yes
before_script:
- [[ "$WITH_RUGGED" == 'no' ]] || gem install rugged
notifications:
  email: false
  irc:
    channels:
    - secure: YQqAJcDMy2Dn54HUly9J9dZhrogEL/wkNVsay0lt06a+Iosw25ba1VKWA8gjmozd3x2LzhEtWyN0zxzGrVXznbtB00lW1l8V8WeM3KRxzC/ymCS4PhqGgGPDnStiAtUFvXkeMihUGcEjSbD0U3s8tpmVttcdQQVhUjSHquomYw8=
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
